import { body } from 'express-validator'

export const nameValidation = body('name')
    .exists()
    .withMessage('Name is required')
    .isString()
    .withMessage('Name must be a string')
    .trim()
    .isLength({ min: 1, max: 15 })
    .withMessage('Name must be between 1 and 15 characters')

export const descriptionValidation = body('description')
    .exists()
    .withMessage('Description is required')
    .isString()
    .withMessage('Description must be a string')
    .trim()
    .isLength({ min: 1, max: 500 })
    .withMessage('Description must be between 1 and 500 characters')

export const websiteUrlValidation = body('websiteUrl')
    .exists()
    .withMessage('Website URL is required')
    .isString()
    .withMessage('Website URL must be a string')
    .trim()
    .matches(
        /^https:\/\/([a-zA-Z0-9_-]+\.)+[a-zA-Z0-9_-]+(\/[a-zA-Z0-9_-]+)*\/?$/
    )
    .withMessage('Website URL must be a valid URL')
    .isLength({ min: 1, max: 100 })
    .withMessage('Website URL must be between 1 and 100 characters')

export const titleValidation = body('title')
    .exists()
    .withMessage('Title is required')
    .isString()
    .withMessage('Title must be a string')
    .trim()
    .isLength({ min: 1, max: 30 })
    .withMessage('Title must be between 1 and 30 characters')

export const shortDescriptionValidation = body('shortDescription')
    .exists()
    .withMessage('Short description is required')
    .isString()
    .withMessage('Short description must be a string')
    .trim()
    .isLength({ min: 1, max: 100 })
    .withMessage(
        'Short description must be between 1 and 100 characters'
    )

export const contentValidation = body('content')
    .exists()
    .withMessage('Content is required')
    .isString()
    .withMessage('Content must be a string')
    .trim()
    .isLength({ min: 1, max: 1000 })
    .withMessage('Content must be between 1 and 1000 characters')
