import { param } from 'express-validator'

export const idValidation = param('id')
    .exists()
    .withMessage('ID is required')
    .isString()
    .withMessage('ID must be a string')
    .isLength({ min: 1 })
    .withMessage('ID must not be empty')
    .isMongoId()
    .withMessage('Incorrect format of ObjectId')

export const blogIdValidation = param('blogId')
    .exists()
    .withMessage('ID is required')
    .isString()
    .withMessage('ID must be a string')
    .isLength({ min: 1 })
    .withMessage('ID must not be empty')
    .isMongoId()
    .withMessage('Incorrect format of ObjectId')

export const postIdValidation = param('postId')
    .exists()
    .withMessage('Post ID is required')
    .isString()
    .withMessage('Post ID must be a string')
    .isLength({ min: 1 })
    .withMessage('Post ID must not be empty')
    .isMongoId()
    .withMessage('Incorrect format of ObjectId')
